{% set name = "pyRMT" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyRMT-{{ version }}.tar.gz
  sha256: 1742956f6c42c17f2087f70f9d548b698cfedb049106fb126e66957ae06fa9ca
  patches:
    - fix-sklearn.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - scikit-learn

test:
  imports:
    - pyRMT
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/GGiecold/pyRMT
  summary: 'Python for Random Matrix Theory: cleaning schemes for noisy correlation matrices'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
